name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SCALA_VERSION: ${{matrix.scala}}
    strategy:
      matrix:
        scala: [2_12, 2_13, 0_24]
        script: [mima, e2e, proptest]
        include:
        - scala: 2_12
          script: examples_and_formatting

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-java@v1
      with:
        java-version: 12

    - name: Mount caches
      uses: actions/cache@v2
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.cache/coursier
        key: ${{ runner.os }}-sbt-${{matrix.scala}}-${{matrix.script}}-${{ hashFiles('**/*.sbt') }}

    - name: ${{matrix.script}}
      run: |
        ./${{matrix.script}}.sh
